### PR TITLE
Update README.rst - added print() function to both examples. 

### PR DESCRIPTION
**Pull request by vidyap-xgboost**
Also, added blank lines to increase readability, following [PEP8 Style Guide](https://www.python.org/dev/peps/pep-0008/)

Resolving another part of #115

### CODE REVIEW

**Comment by vidyap-xgboost** [comment]
Another problem I find with current .rst files is that they don't highlight the color for `python` code as it is traditionally done in Markup. Any way to resolve it in .rst? That would drastically increase the readability and bring some clarity as well as the library grows.

**Comment by shankarpandala** [comment]
I have no idea this but I believe this is not with rst that but with the IDE and plugin you are using. Code editors these days support markdown but fail to work with rst.

**Comment by vidyap-xgboost** [comment]
> I have no idea this but I believe this is not with rst that but with the IDE and plugin you are using. Code editors these days support markdown but fail to work with rst.

I use VSCode. But, I am not talking about code being highlighted in the IDE, I am talking about highlighting it right in the README on GitHub. See this for [example](https://www.python.org/dev/peps/pep-0008/).

**Comment by shankarpandala** [comment]
Got it. I think it's better to migrate to markdown overtime. Even I am facing many issues with .rst

**Comment by vidyap-xgboost** [comment]
> Got it. I think it's better to migrate to markdown overtime. Even I am facing many issues with .rst

That would be a wise decision looking at other popular repos. But I want to do some more research and see what are the advantages and disadvantages of using them. From a user perspective, I feel Markdown is the best as it is the easiest to use.

**Comment by shankarpandala** [comment]
@vidyap-xgboost Yes that's true. 

Don't push anything directly to dev and master branches. They need to be updated only through PR's after checking the Travis CI/CD build pass or fail. I am expecting this collaborator access gives you permission to accept the pull requests. Try that when you raise a new pull request.

Also keep your forked repo updated with the changes others are doing. follow below to do that

image

**Comment by vidyap-xgboost** [comment]
Thank you, that helps. 😊

**Pull request merged**
